Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :friendships, only: [:create, :destroy]
  resources :hangouts

  #resources :invitations, only: [:create, :destroy] - not needed because invitations will only be generated by adding guests to hangouts
  #do
    # resources :invitations -- not needed yet -- would be good if creating hangouts you invite guests at the same time
    # resources :users - not needed yet
  #end

  post "hangouts/:id/guests", to: "hangouts#add_guests"

  get "/", to: "sessions#new", as: "signin"
  post "/sessions", to: "sessions#create"

end
